## Import route
#app_import_data:
#    path: /import/{resource}
#    methods: [POST]
#    defaults:
#        _controller: sylius.controller.import_data:importAction

## Export routes for specific settings
#
#app_export_data_customer:
#    path: /export/sylius.customer/{format}
#    methods: [GET]
#    defaults:
#        resource: sylius.customer
#        _controller: sylius.controller.export_data_customer:exportAction
#        _sylius:
#            filterable: true
#            grid: sylius_admin_customer

