services:
    sylius.message_queue_writer:
        class: LWC\ImportExportBundle\Exporter\MqItemWriter
        abstract: true
        public: true

    sylius.message_queue_reader:
        class: LWC\ImportExportBundle\Importer\MqItemReader
        abstract: true
        public: true
