services:
    sylius.exporter.spreadsheet_writer_factory:
        class: LWC\ImportExportBundle\Writer\PortSpreadsheetWriterFactory

    sylius.exporter.spreadsheet_writer:
        class: LWC\ImportExportBundle\Writer\SpreadsheetWriter
        arguments:
            - '@sylius.exporter.spreadsheet_writer_factory'

    # Spreadsheet-Exporters

#    sylius.exporter.customers.xlsx:
#        class: LWC\ImportExportBundle\Exporter\ResourceExporter
#        arguments:
#            - "@sylius.exporter.spreadsheet_writer"
#            - "@sylius.exporter.pluginpool.customers"
#            - ["Email", "Email_canonical", "First_name" , "Last_name" ,  "Birthday", "Gender", "Phone_number", "Subscribed_to_newsletter"]
#            - "@sylius.exporters_transformer_pool"
#        tags:
#            - { name: sylius.exporter, type: sylius.customer, format: xlsx }
