services:
    sylius.csv_writer:
        class: Port\Csv\CsvWriter
        arguments:
            - ','

    sylius.exporter.csv_writer:
        class: LWC\ImportExportBundle\Writer\CsvWriter
        arguments:
            - '@sylius.csv_writer'

    # CSV-Exporters

#    sylius.exporter.customers.csv:
#        class: LWC\ImportExportBundle\Exporter\ResourceExporter
#        arguments:
#            - "@sylius.exporter.csv_writer"
#            - "@sylius.exporter.pluginpool.customers"
#            - ["Email", "Email_canonical", "First_name" , "Last_name" ,  "Birthday", "Gender", "Phone_number", "Subscribed_to_newsletter"]
#            - "@sylius.exporters_transformer_pool"
#        tags:
#            - { name: sylius.exporter, type: sylius.customer, format: csv }
#
