services:
    sylius.factory.spreadsheet_reader:
        class: Port\Spreadsheet\SpreadsheetReaderFactory
        arguments:
            - 1

    # Spreadsheet-Importers

#    sylius.importer.customer_group.xlsx:
#        class: LWC\ImportExportBundle\Importer\ResourceImporter
#        arguments:
#            - "@sylius.factory.spreadsheet_reader"
#            - "@sylius.manager.customer_group"
#            - "@sylius.processor.customer_groups"
#            - "@sylius.importer.result"
#            - "%sylius.importer.batch_size%"
#            - "%sylius.importer.fail_on_incomplete%"
#            - "%sylius.importer.stop_on_failure%"
#        tags:
#            - { name: sylius.importer, type: customer_group, format: xlsx }
